spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      mode: always
  data:
    jdbc:
      dialect: mysql